---
title: "README"
author: "Qi Qi"
date: "9/6/2018"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## My system and software information
My laptop is macbook and system is macOS High Sierra 10.13.6. Platform is x86_64-apple-darwin15.6.0 (64-bit). R version is 3.5.1 (2018-07-02).

## The problems and solutions

At the very beginning, when I tried to install rmarkdown and bookdown, I was asked to install latex on my computer. Then I installed mactex.

In the process of compiling to html file, there were some error messages about lack of some R packages. I googled and installed those packages via "install.packages()" or "devtools::install_github("hadley/**")".

Error mesaages also showed that Xcode, Xquartz and pandoc are required, so I just installed them.

Then I successfully compiled html version of this book. 

However, in the process to compile pdf file, there was an error message: "! Missing { inserted.
<to be read again> 
                   \__um_group_begin: 
l.13355 \(f_\mathbf
                   {x}(\lambda)\) instead of \(f(\lambda, \mathbf{x})\). In R, 
Here is how much of TeX's memory you used:
 30455 strings out of 492970
 553280 string characters out of 6133938
 771835 words of memory out of 5000000
 34070 multiletter control sequences out of 15000+600000
 536751 words of font info for 92 fonts, out of 8000000 for 9000
 1348 hyphenation exceptions out of 8191
 60i,8n,117p,10414b,665s stack positions out of 5000i,500n,10000p,200000b,80000s

Error: Failed to compile _main.tex. See _main.log for more info.
". I thought this might be caused by some latex package problem. Then I googled and tried in many ways but still couldn't figure it out. Prof.Yan suggested me uninstall mactex and install tinytex. After I did so, I finally got the pdf version of this book.